# Generated by Django 5.1.3 on 2025-03-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin_signup', '0003_remove_customuser_username_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
